environment:
  USERNAME: workspace

services:
  tunnel:
    restart: always
    build:
      context: .
    args:
      username: ${USERNAME}
    hostname: vscode-tunnel
    working_dir: /home/${USERNAME}
    volumes:
      - workspace:/home/${USERNAME}

volumes:
  workspace:
    driver_opts:
      type: none
      device: $PWD/${USERNAME}
      o: bind
      user: "1000:1000"
