# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[[ -z "$FUNCNEST" ]] && export FUNCNEST=100 

bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

if command -v starship > /dev/null; then
    eval "$(starship init bash)"
fi

